# Generated by Django 5.1.3 on 2024-11-15 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_quizprogress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
